### ISSUE TITLE
Sugerencias para las ramas 

### ISSUE THREAD

**Issue by Houssay-grupo4** [Houssay-grupo4/GestionDeCalificaciones#3]
Hola chicas , como andan, teniendo en cuenta el formato de esta actividad , donde nosotros somos los desarrolladores de este sistema de gestion, que les parece usar nuestros nombres para las ramas y, desde ahi , ir subiendo la parte que nos toque despues de dividir el trabajo ?

**Comment by Chiara321** [comment]
Hola, tal vez las ramas deberían llevar el nombre de cada funcionalidad?

**Comment by Paz-Santangelo** [comment]
Buenas tardes. Opino que, como son varias funcionalidades para crear el proyecto, les pongamos el nombre que les correspondan. Por ejemplo: en el principal, podemos poner Menu_Principal y en los demás, Profesor, Preceptor, Alumno, etc.
En estos días, deberíamos tener el backlog, así el sábado comenzamos con el Sprint Planning.
